#!/usr/bin/env bash

echo "u $USER"
echo "su $SUDO_USER"

if [ "x$SUDO_USER" == "x" ]; then
    GUI_USER=$USER
    echo "x$SUDO_USER"
else
    GUI_USER=$SUDO_USER
    echo 2
fi

echo "gu ${GUI_USER}"

echo "Initial wallpaper setup ..."
su ${GUI_USER} bash -c '/usr/bin/php /usr/local/bin/wallpaper/wallpaper.php'
#sudo -u  ${GUI_USER} env XDG_RUNTIME_DIR="/run/user/$(id -u)" echo $DISPLAY && php /usr/local/bin/wallpaper/wallpaper.php
# env DISPLAY=:0.0 XDG_RUNTIME_DIR=/run/user/dzelenika DBUS_SESSION_BUS_ADDRESS="unix:path=${XDG_RUNTIME_DIR}/bus" bash -c "echo $DISPLAY && echo $XDG_RUNTIME_DIR && echo $DBUS_SESSION_BUS_ADDRESS && sudo -u ${GUI_USER} php /usr/local/bin/wallpaper/wallpaper.php"
echo "... done" 





updated="$(crontab -l -u ${GUI_USER} | grep wallpaper/wallpaper.sh | wc -l)"

if [[ $updated ==  "0" ]] ; then
    echo "Cron job doesn't exist. Addding ..."
    echo "Creating crontab file backup."
    cp /var/spool/cron/crontabs/${GUI_USER} /var/spool/cron/crontabs/${GUI_USER}.wp.$(date '+%Y%m%d-%H%M%S').bak
    if [ $? -ne 0 ] ; then
        echo "Can't create backuop. Exiting.";
        exit 1
    fi
    (crontab -l -u ${GUI_USER} 2>/dev/null; echo "* * * * * /usr/local/bin/wallpaper/wallpaper.sh >> /usr/local/bin/wallpaper/wallpaper.log 2>&1") | crontab -u ${GUI_USER} -
    echo "Cron job added."

else
    echo "Cron job already exists. Skipping ..."
fi